### ISSUE TITLE
Assess Chainstack as a Subgraph Hosting provider

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#13]
## 📄 Context
As we will sunset the AWS infrastructure for the subgraph, we are looking for a new subgraph host provider where we don't need to take care of the infra. 

## ✔️ Solution
We will assess the [Chainstack](https://chainstack.com/) to be that provider. 

## 📈 Subtasks

- [x] Check on what protocol and networks are supported. e.g. Ethereum mainnet and testnets (Goerli / Sepolia)
- [x] Check on what monitoring tools are available.
- [x] ~~Verify how the included requests in a Plan work. e.g. is just the request between subgraph <---> archive node, or it also includes the request to the graphQL API~~. **We're moving with the growth plan for now.**
- [x] Deploy PoS for the Goerli and Mainnet network. Considering preview and production environments.

**Comment by brunomenezes** [comment]
Regarding supported networks, on the website, the following protocols are stated as "Coming soon"

1. Arbitrum 
2. Optimism
3. Avalache

**Comment by brunomenezes** [comment]
## Currently Supported Protocols and Networks

```mermaid
flowchart LR
 Ethereum --- A{{Mainnet}}
 Ethereum --- B{{Goerli}}
 Polygon --- C{{Polygon Mumbai Testnet}}
 Polygon --- D{{Polygon Mainnet}}
 P1(BNB Chain) --- E{{BNB Smart Chain Testnet}}
 P1(BNB Chain) --- F{{BNB Smart Chain Mainnet}}
```

**Comment by brunomenezes** [comment]
### Deployment status

✅ Goerli
✅ PoS Mainnet production 
✅ PoS Mainnet Preview
