### ISSUE TITLE
Update Matchstick-AS

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#15]
## 📄 Context
We use the matchstick-as library for unit testing the logic of the handler. It is good to keep up with evolution and not fall behind. Currently, the pos-subgraph and rollups-subgraph packages are using version `0.5.0`.  

## 📈 Subtasks

- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Check the release changelog for new features that could benefit the current base code. 
- [x] Create the corresponding issue if an update requires major work.
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Verify whether everything is working as expected. **i.e. run the tests using the new version.**
