### ISSUE TITLE
Update graph-ts and graph-cli

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#16]
## 📄 Context
We use @graphprotocol/graph-cli and @graphprotocol/graph-ts. The CLI for reading the manifest, compiling the mappings to AssemblyScript and other actions and the `graph-ts` provides APIs to access the graph node store, data on IPFS, etc. We need to upgrade the libraries to their latest version, currently graph-ts@0.31.0 and graph-cli@0.51.2

## 📈 Subtasks

- [ ] Check the changelog for new features or any changes. 
- [ ] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [ ] Create the corresponding issue if an update requires major work.
- [ ] Make sure dependencies are updated in the lock file (yarn.lock).
- [ ] Verify whether everything is working as expected. i.e. Running the tests and indexing a subgraph using the new versions.
