### ISSUE TITLE
Upgrade rollups library to its latest version

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#18]
## 📄 Context
Upgrade the rollups library to its latest version, i.e. **v0.9.1.** 

## 📈 Subtasks

- [x] Update the package.json to the new fixed version ( i.e. no ^ or ~ )
- [x] Create the corresponding issue if an update requires major work.
- [x] Make sure dependencies are updated in the lock file (yarn.lock).
- [x] Verify whether everything is working as expected.
