### ISSUE TITLE
Add deployment automation for PoS [Preview Environment]

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#19]
## 📄 Context
Currently, we do the Subgraph deployment manually. Since we moved to Chainstack and already have Subgraph Hosted Services, it would be good to automate the deployment of our Subgraph solution.

## ✔️ Solution
Create a GitHub action to build and publish the subgraph changes once merged into the `main` branch (target is preview environment). 

## 📈 Subtasks

- [ ] Add required secrets for GitHub Actions:
   - [ ] Secrets to interface with Subgraph Hosted Services API.
   - [ ] Secrets to interface with Chainstack API
- [ ] Create the GitHub action to automate deployment for the `main` branch changes.
   - [ ] Deploy subgraph on Hosted Services. [Preview]
   - [ ] Deploy subgraph on Chainstack service. [Preview]
- [ ] **Add any extra task in case of oversight** [Optional]

## 🎯 Definition of Done

- [ ] Subgraph changes are reflected with success in the Hosted service.
- [ ] Subgraph changes are reflected with success in the Chainstack service.
