### ISSUE TITLE
Remove new Gas-Based pool event handling

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#25]
## 📄 Context
We are streamlining the creation of a staking pool in our front end, offering only the flat-rate option. Today, only 1 gas-based pool is deployed on Mainnet and is "inactive". Hence, also removes the handling of new Gas-based staking pools, stopping the indexing. 

## ✔️ Solution
Remove the handling of `NewGasTaxCommissionStakingPool` in the code. 

Extra info: Gas-based pool on mainnet [0x8fa412526a1a2506a03c1d3b23cdf1f6dcc8bbb1](https://explorer.cartesi.io/stake/0x8fa412526a1a2506a03c1d3b23cdf1f6dcc8bbb1)

## 📈 Subtasks

- [ ] Remove logic to handle `NewGasTaxCommissionStakingPool`
- [ ] Remove any subgraph template declarations
- [ ] Remove any test related to that event handling

## 🎯 Definition of Done

- [ ] **API is not returning any gas-based pool after indexing.** 
- [ ] CI is passing.
