### ISSUE TITLE
Remove eligibility package

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#32]
## 📄 Context
That is a feature we were pursuing in 2021, but it was put on hold, and never came back to the priority list. So it is arguably a candidate to be removed. 

## ✔️ Solution

Remove the package and also the github-action related to that.

## 📈 Subtasks

- [x] Remove the eligibility package
- [x] Remove the github-action `eligibility`
- [x] Remove Eligibility entity type
- [x] Remove references of Eligibility from the template yaml files

**Comment by brunomenezes** [comment]
@tuler, do you agree?
