### ISSUE TITLE
Remove Goerli related content

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/subgraph#37]
## 📄 Context
The Goerli testnet decommission is overdue, and mainly, the technologies supporting it, e.g. Metamask, are starting to remove it as an option, so there is no point in keeping its definitions and code supported here. 

__sidenote: Staking web application is not using it anymore.__

## ✔️ Solution

Remove all code, scripts, and template definitions related to Goerli. Below are a few subtasks for obvious places to check, but don't be limited to that maybe there are other unused networks that could also be removed.

## 📈 Subtasks

- [ ] Update npm-scripts if any.
- [ ] Update subgraph templates, if any.
- [ ] Update graphql schema if necessary.
- [ ] Update hardhat files.

## 🎯 Definition of Done

- [ ] All Goerli related code is removed.

**Comment by nevendyulgerov** [comment]
As per this [comment](https://github.com/cartesi/subgraph/pull/40#issuecomment-2068379572), we can close this one as already tackled.
